name: Deploy Node.js App

on:
  push:
    branches:
     - dev

jobs:
  build-and-deploy:
    runs-on: self-hosted   # 👈 Your own runner instead of GitHub-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --production

      - name: Build Docker image
        run: |
          docker build -t my-node-app .

      - name: Stop old container (if running)
        run: |
          docker rm -f my-node-app || true

      - name: Run Docker container
        run: |
          docker run -d -p 3000:3000 -e RAZORPAY_KEY_ID=rzp_test_6bLKr4BVxTpeRI -e RAZORPAY_KEY_SECRET=I8SllVW1cBGgXbIiEXWphUUJ --name my-node-app my-node-app
